const Etf = require("./etf.js")
module.export.PlanList = [
    {
        time:"20171129",
        state:"normal",
        count:4,
        info:{
            buy:{
                "000478":{
                    num:2,
                    value:2.3738
                },
                "001064":{
                    num:1,
                    value:0.7779
                },
                "003376":{
                    num:1,
                    value:0.9275
                }
            }
        }
        
    },
    {
        time:"20171214",
        state:"normal",
        count:2,
        info:{
            buy:{
                "100032":{
                    num:1,
                    value:"1.3100"
                },
                "502010":{
                    num:1,
                    value:"1.0944"
                }
            }
        }
    },
    {
        time:"120171229",
        state:"normal",
        count:2,
        info:{
            buy:{
                "000478":{
                    num:1,
                    value:"2.3536"
                },
                "100032":{
                    num:1,
                    value:"1.3280"
                }
            }
        }
    }
]