const Etf = require("./etf.js")
module.export.PlanList = [
    {
        time:"2017-11-29",
        state:"normal",
        count:4,
        info:{
            buy:{
                "000478":{
                    num:2,
                    value:2.3738
                },
                "001064":{
                    num:1,
                    value:0.7779
                },
                "003376":{
                    num:1,
                    value:0.9275
                }
            }
        }
        
    },
    {
        time:"2017-12-14",
        state:"normal",
        count:2,
        info:{
            buy:{
                "100032":{
                    num:1,
                    value:"1.3100"
                },
                "502010":{
                    num:1,
                    value:"1.0944"
                }
            }
        }
    },
    {
        time:"2017-12-29",
        state:"normal",
        count:2,
        info:{
            buy:{
                "000478":{
                    num:1,
                    value:"2.3536"
                },
                "100032":{
                    num:1,
                    value:"1.3280"
                }
            }
        }
    },
    {
        time:"2018-1-15",
        state:"self",
        count:1,
        info:{
            buy:{
                "001064":{
                    num1:1,
                    value:"unknown"
                }
            }
        }
    }
]